kafka.bootstrap.servers=${KAFKA_BOOTSTRAP_SERVERS:my-cluster-kafka-bootstrap-kafka.apps.tiago.tiago.to:443}
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=SCRAM-SHA-512
quarkus.openshift.env.mapping.KAFKA_USERNAME.from-secret=kafka-auth
quarkus.openshift.env.mapping.KAFKA_USERNAME.with-key=username
quarkus.openshift.env.mapping.KAFKA_PASSWORD.from-secret=kafka-auth
quarkus.openshift.env.mapping.KAFKA_PASSWORD.with-key=password
# Mount truststore secret into pod and bind env var
quarkus.openshift.mounts.truststore.path=/mnt/truststore
quarkus.openshift.secret-volumes.truststore.secret-name=kafka-client-ssl-secret
quarkus.openshift.env.mapping.TRUSTSTORE_PASSWORD.from-secret=kafka-client-ssl-secret
quarkus.openshift.env.mapping.TRUSTSTORE_PASSWORD.with-key=truststore-password
# kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username=redhat-user password=redhat123;
kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
kafka.ssl.truststore.location=/mnt/truststore/truststore.jks
kafka.ssl.truststore.password=${TRUSTSTORE_PASSWORD}
#topic configuration
mp.messaging.incoming."app.test".connector=smallrye-kafka
mp.messaging.incoming."app.test".topic=app.test.window
mp.messaging.incoming."app.test".key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming."app.test".value.deserializer=org.acme.tracing.messageparams.MqttSendMessageKafkaDeserializer
mp.messaging.incoming."app.test".group.id=cons-streams