quarkus.log.console.enable=true
quarkus.log.level=INFO
quarkus.openshift.deploy=true
quarkus.kubernetes-client.trust-certs=true
quarkus.openshift.env.vars.service=${SERVICE:ws://mqtt-server:8090}
# quarkus.openshift.env.vars.service=${SERVICE:ws://localhost:8090}
