quarkus.log.console.enable=true
quarkus.log.level=INFO
# quarkus.openshift.deploy=true
quarkus.kubernetes-client.trust-certs=true
# quarkus.openshift.env.vars.service=${SERVICE:ws://mqtt-server:8090}
quarkus.openshift.env.vars.service=${SERVICE:tcp://mqtt-server:1883}
# quarkus.openshift.env.vars.service=${SERVICE:ws://localhost:8090}
quarkus.otel.exporter.otlp.traces.endpoint=${OTEL_EXPORTER_OTLP_ENDPOINT:http://dev-collector.openshift-tempo-operator.svc.cluster.local:4317}
quarkus.openshift.env.vars.otel-exporter-otlp-insecure=${OTEL_EXPORTER_OTLP_INSECURE:true}