apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
stringData:
  endpoint: http://minio-service.minio.svc.cluster.local:9000
  bucket: tempo
  access_key_id: minio
  access_key_secret: minio123
type: Opaque