apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keda-pvc
  namespace: openshift-keda
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard