apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: server-scaledobject
  namespace: mqtt
spec:
  scaleTargetRef:
    kind: Deployment 
    name: "mqtt-server"
  cooldownPeriod:  200 
  maxReplicaCount: 30 
  minReplicaCount: 1 
  fallback: 
    failureThreshold: 3
    replicas: 1
  pollingInterval: 10
  triggers:
  - type: prometheus 
    metadata:
      serverAddress: https://thanos-querier.openshift-monitoring.svc.cluster.local:9092 
      namespace: mqtt 
      metricName: http_requests_total
      threshold: '50'
      query: sum by (pod) ( rate(container_network_receive_packets_total{namespace="mqtt", pod=~".*mqtt-server.*" }[1m]))
      ignoreNullValues: "false" 
      unsafeSsl: "false" 
      authModes: "bearer" 
    authenticationRef: 
      name: keda-trigger-auth-prometheus
      kind: TriggerAuthentication