apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: e1be31ab83f8577c8ca38c19c3acc33bb445d9d1
    app.quarkus.io/quarkus-version: 3.19.3
  name: mqtt-producer
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: mqtt-producer
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mqtt-producer
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      labels:  # ✅ This must match the selector above
        app.kubernetes.io/name: mqtt-producer
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - name: mqtt-producer
          image: 'quay.io/rh_ee_tavelino/mqtt-producer'
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: SERVICE
              value: 'ws://mqtt-server:8090'
            - name: JAVA_APP_JAR
              value: /deployments/quarkus-run.jar
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
