kind: Service
apiVersion: v1
metadata:
  name: mqtt-producer
  labels:
    app.kubernetes.io/managed-by: quarkus
    app.kubernetes.io/name: mqtt-producer
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
    app.openshift.io/runtime: quarkus
  annotations:
    app.quarkus.io/quarkus-version: 3.19.3
    app.quarkus.io/vcs-uri: 'https://github.com/TiagoAvelino/loadTest.git'
spec:
  clusterIP: 172.30.40.219
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.40.219
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app.kubernetes.io/name: mqtt-producer
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
