apiVersion: console.streamshub.github.com/v1alpha1
kind: Console
metadata:
  name: my-console
spec:
  hostname: my-console.apps.tiago-cluster.sandbox2998.opentlc.com 
  kafkaClusters:
    - name: my-cluster
      namespace: kafka
      listener: external
      properties:
        values: []
        valuesFrom: []
      credentials:
        kafkaUser:
          name: redhat-user